# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
import random


# Views for Groups

def feed(request):
    i = 1
    journal_data = (
        {'id': 1,
         'student': {'id': 1, 'name': u"Павлюк Андрій"},
         'days': {
         '1': random.randint(0,1),
         '2': random.randint(0,1),
         '3': random.randint(0,1),
         '4': random.randint(0,1),
         '5': random.randint(0,1),
         '6': random.randint(0,1),
         '7': random.randint(0,1),
         '8': random.randint(0,1),
         '9': random.randint(0,1),
         '10': random.randint(0,1),
         '11': random.randint(0,1),
         '12': random.randint(0,1),
         '13': random.randint(0,1),
         '14': random.randint(0,1),
         '15': random.randint(0,1),
         '16': random.randint(0,1),
         '17': random.randint(0,1),
         '18': random.randint(0,1),
         '19': random.randint(0,1),
         '20': random.randint(0,1),
         '21': random.randint(0,1),
         '22': random.randint(0,1),
         '23': random.randint(0,1),
         '24': random.randint(0,1),
         '25': random.randint(0,1),
         '26': random.randint(0,1),
         '27': random.randint(0,1),
         '28': random.randint(0,1),
         '29': random.randint(0,1),
         '30': random.randint(0,1),
         '31': random.randint(0,1)}},

        {'id' : 2,
         'student': {'id': 2, 'name': u"Сорока Людмила"},
         'days': {
         '1': random.randint(0,1),
         '2': random.randint(0,1),
         '3': random.randint(0,1),
         '4': random.randint(0,1),
         '5': random.randint(0,1),
         '6': random.randint(0,1),
         '7': random.randint(0,1),
         '8': random.randint(0,1),
         '9': random.randint(0,1),
         '10': random.randint(0,1),
         '11': random.randint(0,1),
         '12': random.randint(0,1),
         '13': random.randint(0,1),
         '14': random.randint(0,1),
         '15': random.randint(0,1),
         '16': random.randint(0,1),
         '17': random.randint(0,1),
         '18': random.randint(0,1),
         '19': random.randint(0,1),
         '20': random.randint(0,1),
         '21': random.randint(0,1),
         '22': random.randint(0,1),
         '23': random.randint(0,1),
         '24': random.randint(0,1),
         '25': random.randint(0,1),
         '26': random.randint(0,1),
         '27': random.randint(0,1),
         '28': random.randint(0,1),
         '29': random.randint(0,1),
         '30': random.randint(0,1),
         '31': random.randint(0,1)}},

        {'id' : 3,
         'student': {'id': 3, 'name': u"Степан Бандера"},
         'days': {
         '1': random.randint(0,1),
         '2': random.randint(0,1),
         '3': random.randint(0,1),
         '4': random.randint(0,1),
         '5': random.randint(0,1),
         '6': random.randint(0,1),
         '7': random.randint(0,1),
         '8': random.randint(0,1),
         '9': random.randint(0,1),
         '10': random.randint(0,1),
         '11': random.randint(0,1),
         '12': random.randint(0,1),
         '13': random.randint(0,1),
         '14': random.randint(0,1),
         '15': random.randint(0,1),
         '16': random.randint(0,1),
         '17': random.randint(0,1),
         '18': random.randint(0,1),
         '19': random.randint(0,1),
         '20': random.randint(0,1),
         '21': random.randint(0,1),
         '22': random.randint(0,1),
         '23': random.randint(0,1),
         '24': random.randint(0,1),
         '25': random.randint(0,1),
         '26': random.randint(0,1),
         '27': random.randint(0,1),
         '28': random.randint(0,1),
         '29': random.randint(0,1),
         '30': random.randint(0,1),
         '31': random.randint(0,1)}},
    )
    return render(request, 'students/journal.html', {'journal_data': journal_data})